apiVersion: apps/v1
kind: Deployment
metadata:
  name: blog-auth-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: auth
  template:
    metadata:
      labels:
        app: auth
    spec:
      containers:
        - name: auth
          image: ilkiinm03/blog-auth
          env:
            - name: MONGO_URI
              value: "mongodb://blog-auth-mongo-srv:27017/auth"
---
apiVersion: v1
kind: Service
metadata:
  name: blog-auth-srv
spec:
  type: ClusterIP
  selector:
    app: auth
  ports:
    - name: auth
      protocol: TCP
      port: 3000
      targetPort: 3000